#!/usr/bin/env python3
"""
Generate 02_import_data.sql from B2C- Divy - Sheet1.csv
Run from ecom directory: python scripts/generate_import.py
"""
import csv
import re
import os

# Paths relative to script location
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ECOM_DIR = os.path.dirname(SCRIPT_DIR)
CSV_PATH = os.path.join(ECOM_DIR, "B2C- Divy - Sheet1.csv")
OUTPUT_PATH = os.path.join(SCRIPT_DIR, "02_import_data.sql")


def parse_date(date_str):
    """Parse various date formats to SQLite compatible format (YYYY-MM-DD HH:MM:SS) or None."""
    if not date_str or not str(date_str).strip():
        return None

    date_str = str(date_str).strip()

    # DD.MM.YYYY or D.M.YYYY
    m = re.match(r"(\d{1,2})\.(\d{1,2})\.(\d{4})$", date_str)
    if m:
        return f"{m.group(3)}-{m.group(2).zfill(2)}-{m.group(1).zfill(2)} 00:00:00"

    # DD-MM-YYYY or D-M-YYYY
    m = re.match(r"(\d{1,2})-(\d{1,2})-(\d{4})$", date_str)
    if m:
        return f"{m.group(3)}-{m.group(2).zfill(2)}-{m.group(1).zfill(2)} 00:00:00"

    # DD/MM/YYYY or DD/MM/YY
    m = re.match(r"(\d{1,2})/(\d{1,2})/(\d{2,4})$", date_str)
    if m:
        year = m.group(3)
        if len(year) == 2:
            year = "20" + year
        return f"{year}-{m.group(2).zfill(2)}-{m.group(1).zfill(2)} 00:00:00"

    # YYYY-MM-DD
    m = re.match(r"(\d{4})-(\d{1,2})-(\d{1,2})$", date_str)
    if m:
        return f"{m.group(1)}-{m.group(2).zfill(2)}-{m.group(3).zfill(2)} 00:00:00"

    return None


def escape_sql(s):
    """Escape single quotes for SQL. Returns 'NULL' for empty/None."""
    if s is None:
        return "NULL"
    s = str(s).strip()
    if s == "":
        return "NULL"
    s = s.replace("'", "''")
    return f"'{s}'"


def get_row_value(row, key, default=""):
    """Get value from row, handling alternate keys."""
    v = row.get(key, default)
    if v is None or (isinstance(v, str) and v.strip() == ""):
        return default
    return v


def main():
    if not os.path.exists(CSV_PATH):
        print(f"Error: CSV not found at {CSV_PATH}")
        return 1

    rows = []
    with open(CSV_PATH, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            # Skip completely empty rows
            if not any(v and str(v).strip() for v in row.values()):
                continue
            rows.append(row)

    inserts = []
    for row in rows:
        sno = escape_sql(get_row_value(row, "sno", ""))
        lead_no = escape_sql(get_row_value(row, "Lead no.", ""))
        tenure = escape_sql(get_row_value(row, "Tenure", ""))
        date_raw = get_row_value(row, "Date", "")
        parsed_date = parse_date(date_raw) if date_raw else None
        date_val = f"'{parsed_date}'" if parsed_date else "NULL"
        customer = escape_sql(get_row_value(row, "Customer/ Company Name", ""))
        segment = escape_sql(get_row_value(row, "Segment(Product Type)", ""))
        kwp = escape_sql(get_row_value(row, "kWp", ""))
        structure = escape_sql(get_row_value(row, "Structure", ""))
        inverter = escape_sql(get_row_value(row, "Inverter", ""))
        mobile = escape_sql(get_row_value(row, "Mobile No", ""))
        system_type = escape_sql(get_row_value(row, "System type ", get_row_value(row, "System type", "")))
        address = escape_sql(get_row_value(row, "ADDRESS", ""))
        area = escape_sql(get_row_value(row, "Area", ""))
        brand = escape_sql(get_row_value(row, "SOLAR BRAND", ""))

        ins = f"({sno}, {lead_no}, {tenure}, {date_val}, {customer}, {segment}, {kwp}, {structure}, {inverter}, {mobile}, {system_type}, {address}, {area}, {brand})"
        inserts.append(ins)

    sql_lines = [
        "-- Generated by scripts/generate_import.py - DO NOT EDIT",
        "-- Run 01_schema_update.sql first, then this file",
        "",
        "DROP TABLE IF EXISTS TempImport;",
        'CREATE TABLE TempImport (',
        "    sno TEXT,",
        "    leadNo TEXT,",
        "    tenure TEXT,",
        "    date TEXT,",
        "    customerCompanyName TEXT,",
        "    segmentProductType TEXT,",
        "    kWp TEXT,",
        "    structure TEXT,",
        "    inverter TEXT,",
        "    mobileNo TEXT,",
        "    systemType TEXT,",
        "    address TEXT,",
        "    area TEXT,",
        "    solarBrand TEXT",
        ");",
        "",
        "INSERT INTO TempImport (sno, leadNo, tenure, date, customerCompanyName, segmentProductType, kWp, structure, inverter, mobileNo, systemType, address, area, solarBrand) VALUES",
    ]

    for i, ins in enumerate(inserts):
        comma = "," if i < len(inserts) - 1 else ";"
        sql_lines.append(f"    {ins}{comma}")

    sql_lines.extend([
        "",
        "-- Ensure default user exists for imported orders",
        'INSERT OR IGNORE INTO "User" (id, name, email, phone, role, referralCode, createdAt) VALUES',
        "    ('default-user-id', 'System Import User', NULL, '0000000000', 'ADMIN', 'SYSTEM_IMPORT', datetime('now'));",
        "",
        "-- Insert Products from TempImport",
        'INSERT INTO "Product" (',
        "    id, name, description, price, capacity, category, images, isActive, createdAt,",
        "    sno, leadNo, tenure, date, customerCompanyName, segmentProductType, kWp,",
        "    structure, inverter, mobileNo, systemType, address, area, solarBrand",
        ") SELECT",
        "    lower(hex(randomblob(16))),",
        "    COALESCE(NULLIF(trim(customerCompanyName), ''), 'Imported'),",
        "    '',",
        "    0,",
        "    COALESCE(NULLIF(trim(kWp), ''), '0'),",
        "    COALESCE(NULLIF(trim(segmentProductType), ''), 'SPGs'),",
        "    '[]',",
        "    1,",
        "    CASE WHEN date IS NOT NULL AND trim(date) != '' THEN date ELSE datetime('now') END,",
        "    sno, leadNo, tenure,",
        "    CASE WHEN date IS NOT NULL AND trim(date) != '' THEN date ELSE NULL END,",
        "    customerCompanyName, segmentProductType, kWp,",
        "    structure, inverter, mobileNo, systemType, address, area, solarBrand",
        'FROM TempImport;',
        "",
        "-- Insert Orders from TempImport",
        'INSERT INTO "Order" (',
        "    id, orderNumber, userId, status, address, phone, notes, createdAt,",
        "    leadNo, tenure, date, customerCompanyName, segmentProductType, kWp,",
        "    structure, inverter, systemType, area, solarBrand",
        ") SELECT",
        "    lower(hex(randomblob(16))),",
        "    'ORD-' || COALESCE(leadNo, hex(randomblob(4))) || '-' || substr(hex(randomblob(4)), 1, 8),",
        "    'default-user-id',",
        "    'NEW',",
        "    COALESCE(NULLIF(trim(address), ''), 'N/A'),",
        "    COALESCE(NULLIF(trim(mobileNo), ''), '0000000000'),",
        "    customerCompanyName,",
        "    CASE WHEN date IS NOT NULL AND trim(date) != '' THEN date ELSE datetime('now') END,",
        "    leadNo, tenure,",
        "    CASE WHEN date IS NOT NULL AND trim(date) != '' THEN date ELSE NULL END,",
        "    customerCompanyName, segmentProductType, kWp,",
        "    structure, inverter, systemType, area, solarBrand",
        'FROM TempImport;',
        "",
        "DROP TABLE TempImport;",
        "",
        "-- Verification",
        'SELECT COUNT(*) as product_count FROM "Product";',
        'SELECT COUNT(*) as order_count FROM "Order";',
    ])

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"Generated {OUTPUT_PATH} with {len(inserts)} rows from {CSV_PATH}")
    return 0


if __name__ == "__main__":
    exit(main())
